name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install requests
          # Additional dependencies if needed
          # pip install package_name

      - name: Build Windows Executable
        run: |
          pyinstaller --onefile main.py
        working-directory: ${{ github.workspace }}

      - name: Rename Executable
        run: |
          move dist\main.exe dist\goldprice.exe
        working-directory: ${{ github.workspace }}

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: dist/goldprice.exe
